### ISSUE TITLE
mquickAction.addActionItem(faceItem); return nullpointer exeption

### ISSUE THREAD

**Issue by mustafaerturk** [lorensiuswlt/NewQuickAction3D#17]
```
            ActionItem faceItem = new ActionItem(FACEBOOK, "FACEBOOK");
    ActionItem twitItem = new ActionItem(TWİTTER, "TWİTTER");
    ActionItem smsItem = new ActionItem(SMS, "SMS");
    ActionItem emailItem = new ActionItem(EMAİL, "EMAİL");

    QuickAction mquickAction = new QuickAction(this,QuickAction.VERTICAL);
    mquickAction.addActionItem(faceItem);
```

09-25 18:32:44.424: E/ViewRootImpl(24600): sendUserActionEvent() mView == null
09-25 18:32:51.304: E/AndroidRuntime(24600): FATAL EXCEPTION: main
09-25 18:32:51.304: E/AndroidRuntime(24600): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ip_dergi/com.ip_dergi.ItemContent}: java.lang.NullPointerException
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread.access$700(ActivityThread.java:150)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.os.Looper.loop(Looper.java:137)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread.main(ActivityThread.java:5279)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at java.lang.reflect.Method.invokeNative(Native Method)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at java.lang.reflect.Method.invoke(Method.java:511)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at dalvik.system.NativeStart.main(Native Method)
09-25 18:32:51.304: E/AndroidRuntime(24600): Caused by: java.lang.NullPointerException
09-25 18:32:51.304: E/AndroidRuntime(24600):    at net.londatiga.android.QuickAction.addActionItem(QuickAction.java:170)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at com.ip_dergi.ItemContent.onCreate(ItemContent.java:68)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.Activity.performCreate(Activity.java:5267)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
09-25 18:32:51.304: E/AndroidRuntime(24600):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
09-25 18:32:51.304: E/AndroidRuntime(24600):    ... 11 more

**Comment by tomerav0** [comment]
replace 

if (mOrientation == HORIZONTAL) {
            container = mInflater.inflate(R.layout.action_item_horizontal, null);
        } else {
            container = mInflater.inflate(R.layout.action_item_vertical, null);
        }

with 

if (mOrientation == HORIZONTAL) {
            container = mInflater.inflate(R.layout.action_item_horizontal, null, false);
        } else {
            container = mInflater.inflate(R.layout.action_item_vertical, null, false);
        }

in quickaction class
